---
all:
  hosts:
    sonar-01:
      ansible_host: 62.84.124.162
    nexus-01:
      ansible_host: 62.84.127.16
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: maxship